ColorRun.langs = {}

ColorRun.langs["fr"] = {
    ["create_game"] = "Créer une partie",
    ["joinedqueue"] = "%s a rejoint la file d'attente",
    ["leftqueue"] = "%s a quitté la file d'attente",
    ["forceduowith"] = "Vous faites désormais équipe avec: %s !",
    ["start_delayed"] = "Le lancement de la partie a été annulé",
    ["startingin"] = "La partie commence dans %ss.",
    ["already_in_queue"] = "Vous êtes déjà dans la file d'attente",
    ["join_queue"] = "Rejoindre la file d'attente",
    ["exit"] = "Quitter",

    ["my_team"] = "Mon équipe",
    ["owner"] = "Chef de l'équipe",
    ["member"] = "Membre de l'équipe",

    ["invite_member"] = "Inviter un joueur",
    ["invited_by"] = "%s vous a invité dans son équipe",
    ["invited_who"] = "Vous avez invité %s dans votre équipe",
    ["already_invited"] = "%s a déjà une invitation en attente",
    ["canceled_by"] = "%s a annulé son invitation",
    ["you_has_kick"] = "Vous avez viré %s de votre équipe",
    ["you_get_kick"] = "Vous avez été viré par %s",
    ["left_team"] = "%s à quitté l'équipe.",
    ["you_left_team"] = "Vous avez quitté l'équipe.",
    ["member_join"] = "%s a rejoint votre équipe",
    ["member_disconnect"] = "%s a deconnecté et a quitté votre équipe",

    ["create_game"] = "Créer une partie",
    ["gamemodes"] = "Modes de jeux",
    ["players_max"] = "Joueurs maximum",
    ["rounds_number"] = "Nombre de rounds",
    ["enable_bonuses"] = "Activer les rounds bonus (2 points par round)",
    ["duo_mode"] = "Activer le mode duo",
    ["create_game"] = "Créer la partie",
}

ColorRun.langs["en"] = {
    ["create_game"] = "Create a game",
    ["joinedqueue"] = "%s has joined the queue",
    ["already_in_queue"] = "You are already in queue",
    ["join_queue"] = "Join queue",
    ["start_delayed"] = "The game starting countdown is cancelled",
    ["leftqueue"] = "%s has left the queue",
    ["forceduowith"] = "Your now teaming with: %s !",
    ["exit"] = "Exit",

    ["my_team"] = "My Team",
    ["owner"] = "Team's leader",
    ["member"] = "Team's member",

    ["invite_member"] = "Invite a player",
    ["invited_by"] = "%s invited you in her team",
    ["invited_who"] = "You has invited %s in your team",
    ["already_invited"] = "%s has already an pending invitation",
    ["canceled_by"] = "Invitation canceled by %s",
    ["you_has_kick"] = "You has kicked %s from your team",
    ["you_get_kick"] = "You get kicked by %s",
    ["left_team"] = "%s left the team.",
    ["you_left_team"] = "You left the team.",
    ["member_join"] = "%s has joined your team",
    ["member_disconnect"] = "%s has disconnected and leave your team",
    
    ["create_game"] = "Create game",
    ["gamemodes"] = "Gamemodes",
    ["players_max"] = "Players Max",
    ["rounds_number"] = "Rounds number",
    ["enable_bonuses"] = "Enable bonuses rounds (2 points per rounds)",
    ["duo_mode"] = "Enable duo mode",
    ["create_game"] = "Create game",
}